### ISSUE TITLE
How to use when src changes dinamically

### ISSUE THREAD

**Issue by ivansammartino** [bfred-it/object-fit-images#10]
Hi, I just tried with [Jasny Image Upload widget](http://www.jasny.net/bootstrap/javascript/#fileinput) for Bootstrap but it seems not to work, I suppose because image is loaded at runtime...
Any help, please?
Thank you

**Comment by fregante** [comment]
If you run `objectFitImages()` without any arguments, it will track existing and new images, whether they just change the `src` attribute or they are new `<img>` tags, like in your case.

Make sure that you have the `font-family` set like the readme describes before you run `objectFitImages()`

Perhaps you need

``` css
.thumbnail {
    object-fit: cover;
    font-family: 'object-fit: cover"
}
```
