### ISSUE TITLE
Changing to `fill` after some other value will fail

### ISSUE THREAD

**Issue by fregante** [bfred-it/object-fit-images#18]
This will fail when making the window bigger because `fill` currently skips any processing, including the necessary "reset", which should now be set with `background-size: 100% 100%`

``` css
                            img { object-fit: fill }
@media (max-width: 500px) { img { object-fit: contain } }
```
