### ISSUE TITLE
Change API in v3

### ISSUE THREAD

**Issue by fregante** [bfred-it/object-fit-images#19]
Using `font-family` is not necessary most of the time; the module could become leaner and with less restrictions (e.g. `object-fit` has to always live with `object-position` inside `font-family`) by just storing the values inside `background-size` and `background-position`
## Example

``` css
img {
    object-fit: fill; background-size: 100% 100%;
}
img {
    object-fit: cover; background-size: cover;
    object-position: bottom; background-position: bottom;
}
```
## Table with equivalent values for `object-fit`

| Native | For polyfill |
| --- | --- |
| `object-fit: cover` | `background-size: cover` |
| `object-fit: contain` | `background-size: contain` |
| `object-fit: fill` | `background-size: 100% 100%` |
| `object-fit: none` | `background-size: auto` |
| `object-fit: scale-down` | `font-family: 'object-fit: scale-down'` |
## Table with equivalent values for `object-position`

| Native | For polyfill |
| --- | --- |
| `object-position: <any>` | `background-position: <any>` |

`object-position` would be pretty straightforward as it's a 1:1 match with `background-position`
