### ISSUE TITLE
react.js support

### ISSUE THREAD

**Issue by sktt** [bfred-it/object-fit-images#29]
Hello I'd like to use this for a React.js application where i have object-fit and object-position for a spritesheet.

I have my react component programmatically set the style. React will however automagically strip fontFamily:.. from the element. Would it be possible to come around this?

**Comment by fregante** [comment]
What's stripping `fontFamily` exactly and why?

**Comment by sktt** [comment]
I thought it was react, it is actually my browser (chrome) that removes it.

**Comment by fregante** [comment]
If it's being removed it's probably invalid, make sure it has the quotes:

``` css
.img {
   object-fit: contain;
   font-family: 'object-fit: contain'; /*correct*/
}
```

This is invalid CSS:

``` css
.img {
   object-fit: contain;
   font-family: object-fit: contain; /*wrong*/
}
```

---

In JS: 

``` js
img.style.fontFamily = "'object-fit: contain'"; /* correct */
img.style.fontFamily = "object-fit: contain";   /* wrong */
```
