### ISSUE TITLE
Cannot Print Images in Edge

### ISSUE THREAD

**Issue by gary-inno** [bfred-it/object-fit-images#47]
Images can be printed before fix but not after fix. See demo page.

**Comment by fregante** [comment]
There's no fix for that unfortunately, other than using alternative libraries that use wrapper elements

## Edit

All browsers have the setting **Print Background Colors and Images.** This unfortunately is a user setting that we don't have access to, but you may be able to either inform the user of this.

Alternatively, show non-`object-fit` images when the user prints. This can be done via `print` CSS file (for example by having an untouched hidden `<img>` just for printing)


```css
img.object-fit {
  object-fit: cover;
  font-family: 'object-fit: cover;';
}
img.print-only {
  display: none;
}
@media print {
  img.object-fit {
    display: none;
  }
  img.print-only {
    display: block;
  }
}
```

**Comment by mattgreenfield** [comment]
Couldn't you add some print CSS? Something like this. (although I'm not actually sure what CSS is stopping it currently)

``` css
@media print {
   img {
    display: block;
    position: relative;
  }
}

```
