### ISSUE TITLE
Callback support

### ISSUE THREAD

**Issue by ib4** [bfred-it/object-fit-images#50]
Is it possible to add support for passing a callback function to fire after each image is changed? I'm hiding all images using object-fit in non-supported browsers, with opacity 0 in CSS, and manually set the opacity to 1 after running the script - which I would like to do in the callback.

**Comment by fregante** [comment]
How do you mark which images use object-fit? Are you using a class?

You can probably already do

```js
objectFitImages('.your-class');
$('.your-class').css('opacity', 1);
```

objectFitImages is synchronous so wherever you call it you can directly also set the opacity to 1

**Comment by fregante** [comment]
Here's a IE10+ CSS-only solution:

```css
@keyframes fadein { /* needs prefixes */
    from {
        opacity: 0;
    }
}
img {
    object-fit: cover;
    font-family: 'object-fit: cover';
    animation: fadein 1s backwards paused;
}
img[src^="data:"] {
    animation-play-state: running;
}
```
