### ISSUE TITLE
Cannot override with CSS alone

### ISSUE THREAD

**Issue by lesliecdubs** [bfred-it/object-fit-images#54]
Hi! It would be extremely useful to be able to use this polyfill on elements, but also have the ability to override it at certain breakpoints using CSS only.

For example, I often want an element to have `object-fit: contain` on mobile views, but then at my large breakpoint I want to override it with `object-fit: none`. Because this plugin adds a background image in IE to mimic the object-fit functionality, it cannot later be overriden with only CSS.

**Comment by fregante** [comment]
OFI works when you define the `font-family` as instructed in the readme. Use that property in the media query as well **and** enable `watchMQ` to make sure any changes made by Media Queries are picked up by OFI.

**Comment by lesliecdubs** [comment]
@bfred-it I did use the font-family as instructed in the readme. For instance:

```
.img-element {
  height: 100%;
  font-family: 'object-fit: contain;';
  object-fit: cover;
  width: 100%;

  @include breakpoint(lg) {
    font-family: none;
    object-fit: none;
    height: auto;
  }
}
```

On window load, I was running `objectFitImages(null, {watchMQ: true});`. The override in the CSS above wasn't working with this setup -- upon hitting the large breakpoint, the background image generated by OFI still existed and did not get removed.

Does the objectFitImages function have to get re-run on the document resize event as well?

**Comment by bfred-it** [comment]
It's not `font-family: none` but `font-family: "object-fit: none"`

**Comment by bfred-it** [comment]
watchMQ is what enables OFI to run automatically on resize

**Comment by fregante** [comment]
It's not `font-family: none` but `font-family: "object-fit: none"`

watchMQ is what enables OFI to run automatically on resize. 

Also are you sure you're not looking for `object-fit: fill`? That's the initial value; `none` is a different behavior

**Comment by lesliecdubs** [comment]
Thanks @bfred-it, that helped. Might be useful to update the readme to be a bit more explicit about how overrides work.

Is there a way to completely get rid of the background image polyfill at a specific breakpoint? Basically I want to go from `object-fit: cover` on mobile to a normal inline image with `max-width: 100%` on desktop.

**Comment by fregante** [comment]
OFI just follows the CSS you feed it.

So if in a normal browser this is your code:

```css
@media (max-width: 100px) {
    img {
        object-fit: cover;
        width: 100px;
        height: 100px;
    }
}
```

This would be your equivalent `ofi` code

```css
@media (max-width: 100px) {
    img {
        object-fit: cover;
        font-family: 'object-fit: cover';
        width: 100px;
        height: 100px;
    }
}
```

---

If instead you need to re-set it:

```css
img {
    object-fit: cover;
    font-family: 'object-fit: cover';
}
@media (max-width: 100px) {
    img {
        object-fit: fill;
        font-family: 'object-fit: fill';
        width: 100px;
        height: 100px;
    }
}
```

---

This is already covered by the docs: When you set `object-fit` you also need to set `font-family` to include the value of `object-fit` as a string.

You can see it working in the new demo: https://bfred-it.github.io/object-fit-images/demo/


--- 

Since you're using SCSS, perhaps its mixin can make it easier: https://github.com/bfred-it/object-fit-images/blob/master/preprocessors/mixin.scss
