### ISSUE TITLE
myclass:hover does not work

### ISSUE THREAD

**Issue by saboco** [bfred-it/object-fit-images#55]
One use case for `object-fit` and `object-position` is to be able to _animate_ the images. One common way to animate is by changing the `object-position` when hovering the image with the mouse cursor.

This does not work.
```
.my-image {
	object-position: -358px -15px;
	font-family: 'object-fit: cover;object-position: -358px -15px;';
	height: 95px;
}

	.my-image:hover {
		object-position: -1140px -15px;
		font-family: 'object-fit: cover;object-position: -1140px -15px;';
	}

```

**Comment by fregante** [comment]
`:hover` is not exactly supported but since OFI uses `background-position` for `object-position`, in the hover avoid `font-family` and only set `background-position`

**Comment by fregante** [comment]
```css
.my-image {
	object-fit: cover;
	font-family: 'object-fit: cover';
	object-position: -358px -15px;
	background-position: -358px -15px;
	height: 95px;
}

	.my-image:hover {
		object-position: -1140px -15px;
		background-position: -1140px -15px;
	}
```
